### ISSUE TITLE
Basic example doesnt work

### ISSUE THREAD

**Issue by blackalgorithm** [FriendsOfPHP/Goutte#256]
Hello,

I just started today to take a look to this library. I tried to run the basic example in the main page but i didn't succeed.
The problem I have is that the return object of $crawler = $client->request('GET', 'http://www.symfony.com/blog/') is not a Crawler Objet but a Response Object so cannot use the Crawlers methods.
Therefore this doesnt work,  (I guess something is missing): 
$link = $crawler->selectLink('Security Advisories')->link();

Also this function doesnt work  
$client->getClient()->setDefaultOption('config/curl/'.CURLOPT_TIMEOUT, 60);

Thanks
BR

**Comment by fittiger** [comment]
me too ...

**Comment by aik099** [comment]
Please send a PR with a fix.

**Comment by georaldc** [comment]
It's because some parts of the documentation is outdated. I've submitted a PR in the past with a readme update that addresses the CURL timeout example

https://github.com/FriendsOfPHP/Goutte/pull/238

@blackalgorithm the selectLink method should work though. I've tested it just now. Maybe it was broken before, but it has always given back a Symfony DomCrawler component.
