### ISSUE TITLE
Get images source from specific div.

### ISSUE THREAD

**Issue by SAMsamani** [FriendsOfPHP/Goutte#310]
Hi,
I'm trying to get source of images which are in a div by id="demo".
Here's what I did:
```
$crawler->filter('#demo img')->each(function ($node) {
    $src = $node->attr('src');
    echo $src . '<br>';
});
```
It doesn't work But if you try getting any other attribute like image height or image class , it works fine.
It only doesn't work when you pass `src` in `attr()`.

**Comment by amirgee007** [comment]
<div class="product-image-wrapper">
		<a href=">
			<img class="" src="" data-src="" alt="Avfuktningspåsar Silica Gel 30x" >
		</a>
	</div>

how to get this image? that's is in the a tag

**Comment by petrk94** [comment]
@amirgee007 
I just had the same problem for my application. With this code you get the link to the image.
To save the image, I think you can use wget/curl or file_get_contents.
here is my code what worked for me to get the image:

Instead of echo the ouput (echo $crawler->filter('#demo img')->eq(0)->attr('src');)
use a variable $linktoimage = $crawler->filter('#demo img')->eq(0)->attr('src');
Than put the variable to file_get_contents and proceed with the code below

$image_stream = file_get_contents($linktoimage);
$file = "my_image.jpg";
file_put_contents($file, $image_stream);

**Comment by mansourian2018** [comment]
hello you can get file address and get file by php copy function like:
`copy($url,$localAdress);`

**Comment by katesaikishore** [comment]
$client = new Client();   
$crawler = $client->request('GET', 'https://factly.in/category/english/');
 echo $crawler->filter('.image img')->eq(0)->attr('src');

![Screenshot 2021-02-08 at 2 25 41 PM](https://user-images.githubusercontent.com/10182914/107198506-31f91200-6a1b-11eb-9c3e-6a86f84924c1.png)
I am unable to get the image
please help me

**Comment by amirgee007** [comment]
hi, its look like we dont have any separate img tag as they added a link for the image tag under A tag.

So you can try it like this.

`$path = 'https://factly.in/category/english/';

        $crawler = $client->request('GET', $path);


        $crawler->filter('.highlights')->each(function ($node) use ($domain) {

            try{
                $text = $node->filter('a')->html();

                preg_match("<img.*?src=[\"\"'](?<url>.*?)[\"\"'].*?>",$text,$output);


                dd($output['url']);
            }
            catch (\Exception $e){
                #dd($e);
            }

        });`

**Comment by amirgee007** [comment]
`$path = 'https://factly.in/category/english/';

        $crawler = $client->request('GET', $path);

        $crawler->filter('.image-link ')->each(function ($node)  {

            $link = $node->filter('img')->attr('src');
            dd($link);
        });`

**Comment by katesaikishore** [comment]
Awesome thanks @amirgee007

**Comment by yossefEl** [comment]
> `$path = 'https://factly.in/category/english/';
> 
> ```
>     $crawler = $client->request('GET', $path);
> 
>     $crawler->filter('.image-link ')->each(function ($node)  {
> 
>         $link = $node->filter('img')->attr('src');
>         dd($link);
>     });`
> ```

Thank you, but sometimes this script doesn't work, for example in my case instead of returning the URI of the image it return the following data : 
"data:image/svg+xml;nitro-empty-id=NTU4OjIwOQ==-1;base64,PHN2ZyB2aWV3Qm94PSIwIDAgMTYxOSAxMDgwIiB3aWR0aD0iMTYxOSIgaGVpZ2h0PSIxMDgwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjwvc3ZnPg==",
If anyone fixed this issue, please list it here and Thanks in advance!
